# -*- mode: ruby -*-
# vim: ft=ruby


# ---- Configuration variables ----

GUI               = false # Enable/Disable GUI
RAM               = 1024   # Default memory size in MB

# Network configuration
DOMAIN            = ".nat.example.com"

# Default Virtualbox .box
# See: https://wiki.debian.org/Teams/Cloud/VagrantBaseBoxes
BOX               = 'centos/7'


HOSTS = {
   "nodejs" => [RAM, GUI, BOX],
}

ANSIBLE_INVENTORY_DIR = 'inventory'

# ---- Vagrant configuration ----

Vagrant.configure(2) do |config|
  HOSTS.each do | (name, cfg) |
    ram, gui, box = cfg



    config.vm.define name do |machine|
      machine.vm.box   = box

      machine.vm.provider "virtualbox" do |vbox|
        vbox.gui    = gui
        vbox.memory = ram
      end

      machine.vm.hostname = name + DOMAIN
      machine.vm.network "private_network", type: "dhcp"
      machine.vm.network "public_network", type: "dhcp"
    end
  end # HOSTS-each

  config.vm.provision "vai" do |ansible|
    ansible.inventory_dir=ANSIBLE_INVENTORY_DIR
    ansible.inventory_filename="hosts"
    # optional: add a group listing all vagrant machines
    ansible.groups = {
      'nodejs' => [ "nodejs" ],
    #  '_provided_by_vagrant_'=> HOSTS.keys,
    }
  end

end